### ISSUE TITLE
⚡️ [Feat] 엔티티 생성

### ISSUE THREAD

**Issue by seungheon123** [boostcampwm-2024/web20-camon#117]
### 📣Task 이름

엔티티 생성

### ✅ 작업 리스트

- [x] Member 모듈 생성
- [x] Broadcast 모듈 생성
- [x] Attendance 모듈 생성
