### ISSUE TITLE
[Chore] api에 swagger 적용

### ISSUE THREAD

**Issue by huiseon37** [boostcampwm-2024/web20-camon#192]
### 📣Task 이름

api에 swagger 적용

### ✅ 작업 리스트

- [ ] 방송 리스트 조회 api에 적용
- [ ] 방송 제목 수정 api에 적용
- [ ] 방송 하단 정보 조회 api에 적용
