### ISSUE TITLE
⚡️ [Feat] broadcast 종료 시, 연쇄 로직 구현

### ISSUE THREAD

**Issue by g00hyun** [boostcampwm-2024/web20-camon#193]
### 📣Task 이름

⚡️ [Feat] broadcast 종료 시, 연쇄 로직 구현

### ✅ 작업 리스트

- [x] broadcast 테이블에서 종료된 방송의 레코드 삭제
- [x] Attendance 테이블에서 종료된 방송의 레코드 생성
- [x] sfu 서버에 broadcast 종료 로직에 연결
