### ISSUE TITLE
⚡️ 로그인 여부에 따른 chat 이벤트 조건 추가

### ISSUE THREAD

**Issue by huiseon37** [boostcampwm-2024/web20-camon#267]
### 📣Task 이름

로그인 여부에 따른 chat 이벤트 조건 추가

### ✅ 작업 리스트

- [x] jwt 가드 구현
- [x] jwt 전략 구현
- [x] chat 이벤트에 가드 연결
