### ISSUE TITLE
⚡️ [Feat] Docker compose을 통한 네트워크 형성

### ISSUE THREAD

**Issue by g00hyun** [boostcampwm-2024/web20-camon#279]
### 📣Task 이름

⚡️ [Feat] Docker compose을 통한 네트워크 형성

### ✅ 작업 리스트

- [x] action script 에러 수정
- [x] docker-compose 적용
- [x] docker-proxy 제거
