### ISSUE TITLE
[Chore] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by seungheon123** [boostcampwm-2024/web20-camon#68]
### 📣Task 이름

프로젝트 초기 설정

### ✅ 작업 리스트

- [x] eslint, Prettier, husky 설정
- [x] 프로젝트 디렉토리 설정 (모노레포)
- [x] typescript 초기 설정
