### ISSUE TITLE
⚡️ 로깅 설정

### ISSUE THREAD

**Issue by seungheon123** [boostcampwm-2024/web20-camon#75]
### 📣Task 이름

로깅 설정

### ✅ 작업 리스트

- [x] 요청에 대한 로그 기록
- [x] 응답에 대한 로그 기록
- [x] 에러에 대한 로그 기록
