### ISSUE TITLE
[Feat] husky로 테스트 자동 실행

### ISSUE THREAD

**Issue by seungheon123** [boostcampwm-2024/web20-camon#76]
### 📣Task 이름

husky로 테스트 자동 실행

### ✅ 작업 리스트

- [x] pre-commint 수정
- [x] e2e, unit 실패 시 commit rollback
- [x] jest 설치
- [x] 가능하면 디렉토리에 맞게 e2e, unit 실행
