### ISSUE TITLE
[Chore] media 서버 초기 설정

### ISSUE THREAD

**Issue by g00hyun** [boostcampwm-2024/web20-camon#89]
### 📣Task 이름

media 서버 초기 설정

### ✅ 작업 리스트

- [x] nest 설치
- [x] 인터셉터 및 필터 설정
- [x] test 환경 연결
- [x] env를 통한 프로필 관리 및 포트 연결
- [x] mysql 데이터베이스 연결
- [x] 배포 파이프라인 작성

### 제외 설정
- logger 설정은 media 서버에서 현재 제외 상태
- redis 데이터베이스 연결
  - 이유
    - subnet 위치 미정
    - private으로 가정 하고 설정 시, 아래와 같은 오류로 인한 설정 지연
      - Redis 연결 재시도 한계 초과
      - 이벤트 리스너 메모리 누수 경고
